### ISSUE TITLE
Support for `include` in DSL

### ISSUE THREAD

**Issue by wagenet** [livingsocial/rake-pipeline#18]
Would be nice to be able to `include` from within the DSL for use of things like `Rake::Pipeline::Web::Filters`.

**Comment by dudleyf** [comment]
I can't think of a way to do this that's not gross and/or complicated. If we started using helper methods for each filter instead of using `filter` directly, it would obviate the need to shorten those long module paths. I could move the `OrderingConcatFilter` and the `concat` helper from https://github.com/wycats/rake-pipeline-web-filters into core and fix rpwf to include the helpers by default. @wycats thoughts?

**Comment by wycats** [comment]
Seems good :)
